name: Deploy App

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [Testing]
    types:
      - completed

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    # only run if testing is successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku (Server)
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "photoshare-fs-server"
          heroku_email: "soekhantaung16@gmail.com"
          appdir: "server"

  deploy-client:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://photoshare-client.herokuapp.com
    needs: deploy-server
    concurrency:
      # wait for server to finish deploying
      group: ${{ format('{0}-{1}', github.workflow, github.job) }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Heroku (Client)
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "photoshare-client"
          heroku_email: "soekhantaung16@gmail.com"
          appdir: "client"
